site_name: Syenasweta
site_url: https://syenasweta.tech
theme:
  name: material
  language: en
  direction: ltr
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js
extra:
  alternate:
    - name: English
      link: /en/ 
      lang: en
    - name: Indonesian
      link: /id/
      lang: id
  homepage: /